homeassistant:
  name: My home assistant

  latitude: !secret home_latitude
  longitude: !secret home_longitude

  currency: UAH
  unit_system: metric

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# cloud:
# config:
# counter:
# dhcp:
# energy:
# frontend:
# history:
# image:
# input_boolean:
# input_datetime:
# input_number:
# input_select:
# input_text:
# logbook:
# map:
# media_source:
# mobile_app:
# my:
# person: !include persons.yaml
# ssdp:
# stream:
# sun:
# system_health:
# tag:
# timer:
# updater:
# usb:
# webhook:
# zeroconf:
# zone:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml